---

- name: Report tuned version
  debug:
    msg: "INFO: The installed version of package tuned is: {{ ansible_facts.packages['tuned'][0].version }}"

- name: Get status of tuned
  command: systemctl status tuned
  register: tuned_status
  ignore_errors: yes
  changed_when: no

- name: Assert that tuned is enabled
  assert:
    that:
      - "'/usr/lib/systemd/system/tuned.service; enabled' in tuned_status.stdout"
    fail_msg: "FAIL: Service tuned is NOT enabled!"
    success_msg: "PASS: Service tuned is enabled."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that tuned is active
  assert:
    that:
      - "'active (running)' in tuned_status.stdout"
    fail_msg: "FAIL: Service tuned is NOT active!"
    success_msg: "PASS: Service tuned is active."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Report tuned-profiles-sap version
  debug:
    msg: "INFO: The installed version of package tuned-profiles-sap is: {{ ansible_facts.packages['tuned-profiles-sap'][0].version }}"

- name: Get active tuned profile
  shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
  check_mode: no
  register: current_profile
  changed_when: false

- debug:
    var: current_profile.stdout_lines, current_profile.stderr_lines

- name: Assert that tuned profile sap-netweaver is currently active
  assert:
    that:
      - current_profile.stdout == 'sap-netweaver'
    fail_msg: "FAIL: The tuned profile 'sap-netweaver' is currently not active!
      Currently active profile: '{{ current_profile.stdout }}'."
    success_msg: "PASS: The tuned profile 'sap-netweaver' is currently active."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

...
