---

- name: Show note number and version
  debug:
    msg: "SAP note {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '2526952') | first).number }}
          (version {{ (__sap_netweaver_preconfigure_sapnotes_versions | selectattr('number', 'match', '2526952') | first).version }}): RHEL for SAP packages"

- name: Report tuned version
  debug:
    msg: "INFO: The installed version of package tuned is: {{ ansible_facts.packages['tuned'][0].version }}"
  when: "'tuned' in ansible_facts.packages"

- name: Assert that tuned.service exists
  assert:
    that: "'tuned.service' in ansible_facts.services"
    fail_msg: "FAIL: Service tuned could not be found!"
    success_msg: "PASS: Service tuned is available."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that tuned is enabled
  assert:
    that: "ansible_facts.services['tuned.service']['status'] == 'enabled'"
    fail_msg: "FAIL: Service tuned is not enabled!"
    success_msg: "PASS: Service tuned is enabled."
  when: "'tuned.service' in ansible_facts.services"
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that tuned is active
  assert:
    that: "ansible_facts.services['tuned.service']['state'] == 'running'"
    fail_msg: "FAIL: Service tuned is not active!"
    success_msg: "PASS: Service tuned is active."
  when: "'tuned.service' in ansible_facts.services"
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- name: Report tuned-profiles-sap-netweaver version
  debug:
    msg: "INFO: The installed version of package tuned-profiles-sap is: {{ ansible_facts.packages['tuned-profiles-sap'][0].version }}"
  when: "'tuned-profiles-sap' in ansible_facts.packages"

- name: Get active tuned profile
  shell: /usr/sbin/tuned-adm active | grep ":" | cut -d ":" -f 2 | awk '{$1=$1;print}'
  check_mode: no
  register: __sap_netweaver_preconfigure_register_current_tuned_profile
  changed_when: false

- debug:
    var: __sap_netweaver_preconfigure_register_current_tuned_profile.stdout_lines, __sap_netweaver_preconfigure_register_current_tuned_profile.stderr_lines

- name: Assert that tuned profile sap-netweaver is currently active
  assert:
    that: "__sap_netweaver_preconfigure_register_current_tuned_profile.stdout == 'sap-netweaver'"
    fail_msg: "FAIL: The tuned profile 'sap-netweaver' is currently not active!
      Currently active profile: '{{ __sap_netweaver_preconfigure_register_current_tuned_profile.stdout }}'."
    success_msg: "PASS: The tuned profile 'sap-netweaver' is currently active."
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"
