---

- name: Check if required packages for SAP NetWeaver are installed
  shell: rpm -q --qf "%{NAME}\n" $(echo {{ __sap_netweaver_preconfigure_packages }} | sed "s.,..g;s,\[,,;s,],,;s,',,g") | grep -v "is not installed"
  register: yum_result
  changed_when: no
  args:
    warn: false

- name: Assert that all required packages for SAP NetWeaver are installed
  assert:
    that:
      - "'{{ line_item }}' in yum_result.stdout_lines"
    fail_msg: "FAIL: Package '{{ line_item }}' is not installed!"
    success_msg: "PASS: Package '{{ line_item }}' is installed."
  with_items:
    - "{{ __sap_netweaver_preconfigure_packages }}"
  loop_control:
    loop_var: line_item
  ignore_errors: "{{ sap_netweaver_preconfigure_assert_ignore_errors|d(false) }}"

- set_fact:
    __sap_netweaver_preconfigure_adobe_doc_services_packages_list: 
      "{{ __sap_netweaver_preconfigure_adobe_doc_services_packages_list|default([]) + 
       [{'name': line_item.split('.')[0], 'arch': line_item.split('.')[1]}] }}"
  with_items: "{{ __sap_netweaver_preconfigure_adobe_doc_services_packages }}"
  loop_control:
    loop_var: line_item
  when: sap_netweaver_preconfigure_use_adobe_doc_services|d(false)

- name: Check if required packages for Adobe Document Services on RHEL 8 are installed
  shell: rpm -q --qf "%{NAME}.%{ARCH}\n" $(echo {{ __sap_netweaver_preconfigure_adobe_doc_services_packages }} | sed "s.,..g;s,\[,,;s,],,;s,',,g") | grep -v "is not installed"
  register: rpm_result
  changed_when: no
  args:
    warn: false
  when: sap_netweaver_preconfigure_use_adobe_doc_services|d(false)

- name: Assert that all required packages for Adobe Document Services are installed
  assert:
    that:
      - "'{{ line_item.name }}.{{ line_item.arch }}' in rpm_result.stdout_lines"
    fail_msg: "FAIL: Package '{{ line_item.name }}.{{ line_item.arch }}' is not installed!"
    success_msg: "PASS: Package '{{ line_item.name }}.{{ line_item.arch }}' is installed."
  with_items: "{{ __sap_netweaver_preconfigure_adobe_doc_services_packages_list }}"
  loop_control:
    loop_var: line_item
  when: sap_netweaver_preconfigure_use_adobe_doc_services|d(false)

...
