---
# tasks file for sap-netweaver-preconfigure configuration

- name: list of required SAP Notes
  debug:
    var: __sap_netweaver_preconfigure_sapnotes | difference([''])

- name: include configuration actions for required sapnotes
  include_tasks: "sapnote/{{ item }}.yml"
  with_items: "{{ __sap_netweaver_preconfigure_sapnotes | difference(['']) }}"

...
