---
# tasks file for sap-netweaver-preconfigure: installation

- name: ensure required packages are installed
  package:
    state: present
    name: "{{ sap_netweaver_preconfigure_packages }}"
  check_mode: "{{ sap_netweaver_preconfigure_installation_check_only }}"
  register: sap_netweaver_preconfigure_packages_result

- name: Get status of installed packages
  yum:
    name: "{{ sap_netweaver_preconfigure_packages }}"
  register: result
  ignore_errors: True
  changed_when: false
- debug:
    var: result.results

...
